/********************************************************************
* ppSRC_ppSRCpackageDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ppSRC_ppSRCpackageDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableppSRC_ppSRCpackageDict();
extern void G__cpp_setup_inheritanceppSRC_ppSRCpackageDict();
extern void G__cpp_setup_typetableppSRC_ppSRCpackageDict();
extern void G__cpp_setup_memvarppSRC_ppSRCpackageDict();
extern void G__cpp_setup_globalppSRC_ppSRCpackageDict();
extern void G__cpp_setup_memfuncppSRC_ppSRCpackageDict();
extern void G__cpp_setup_funcppSRC_ppSRCpackageDict();
extern void G__set_cpp_environmentppSRC_ppSRCpackageDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sample.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ppSRC_ppSRCpackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ppSRC_ppSRCpackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ppSRC_ppSRCpackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ppSRC_ppSRCpackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ppSRC_ppSRCpackageDictLN_sample;

/* STUB derived class for protected member access */
